import {SemanticVersion} from "../src/SemanticVersion/SemanticVersion"
import {XcodeVersionRepositoryMock} from "./mock/XcodeVersionRepositoryMock"
import {XcodeVersionMatcher} from "../src/XcodeVersion/XcodeVersionMatcher"

test("It returns null when repository is empty", () => {
  const repository = new XcodeVersionRepositoryMock()
  const needle = new SemanticVersion(14, null, null)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).toBeNull()
})

test("It finds version based on major component", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersion(14, null, null)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(14)
  expect(xcodeVersion?.version.minor).toEqual(3)
  expect(xcodeVersion?.version.patch).toEqual(1)
})

test("It finds version based on major and minor components", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersion(14, 3, null)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(14)
  expect(xcodeVersion?.version.minor).toEqual(3)
  expect(xcodeVersion?.version.patch).toEqual(2)
})

test("It finds version based on major, minor, and patch components", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersion(14, 3, 1)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(14)
  expect(xcodeVersion?.version.minor).toEqual(3)
  expect(xcodeVersion?.version.patch).toEqual(1)
})

test("It returns null when no version matches major, minor, and patch components", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersion(14, 3, 4)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).toBeNull()
})

test("It returns null when no version matches major and minor components", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersion(14, 5, null)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).toBeNull()
})

test("It returns null when no version matches major component", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersion(16, null, null)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).toBeNull()
})

test("It matches a zero minor component against a null minor component in Xcode version", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15, null, null)
  const needle = new SemanticVersion(15, 0, null)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
})

test("It matches a zero patch component against a null patch component in Xcode version", () => {
  const repository = new XcodeVersionRepositoryMock()
  repository.addXcodeVersion(15, 0, null)
  const needle = new SemanticVersion(15, 0, 0)
  const matcher = new XcodeVersionMatcher(repository)
  const xcodeVersion = matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
})
