import SemanticVersionTemplate, {
  SemanticVersionTemplatePlaceholder
} from "../src/SemanticVersion/SemanticVersionTemplate"
import MockXcodeVersionRepository from "./mock/MockXcodeVersionRepository"
import XcodeVersionMatcher from "../src/XcodeVersion/XcodeVersionMatcher"

test("It throws when repository is empty", async () => {
  const repository = new MockXcodeVersionRepository()
  const needle = new SemanticVersionTemplate(14, 3, 1)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  await expect(matcher.findXcodeVersion(needle)).rejects.toThrow()
})

test("It finds version based on major component", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersionTemplate(14, SemanticVersionTemplatePlaceholder, SemanticVersionTemplatePlaceholder)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  const xcodeVersion = await matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(14)
  expect(xcodeVersion?.version.minor).toEqual(3)
  expect(xcodeVersion?.version.patch).toEqual(1)
})

test("It finds version based on major and minor components", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersionTemplate(14, 3, SemanticVersionTemplatePlaceholder)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  const xcodeVersion = await matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(14)
  expect(xcodeVersion?.version.minor).toEqual(3)
  expect(xcodeVersion?.version.patch).toEqual(2)
})

test("It finds version based on major, minor, and patch components", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersionTemplate(14, 3, 1)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  const xcodeVersion = await matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(14)
  expect(xcodeVersion?.version.minor).toEqual(3)
  expect(xcodeVersion?.version.patch).toEqual(1)
})

test("It throws when no version matches major, minor, and patch components", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersionTemplate(14, 3, 4)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  await expect(matcher.findXcodeVersion(needle)).rejects.toThrow()
})

test("It throws when no version matches major and minor components", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersionTemplate(14, 5, SemanticVersionTemplatePlaceholder)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  await expect(matcher.findXcodeVersion(needle)).rejects.toThrow()
})

test("It throws when no version matches major component", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(15)
  repository.addXcodeVersion(14, 4, 2)
  repository.addXcodeVersion(14, 3, 2)
  repository.addXcodeVersion(14, 3, 1)
  repository.addXcodeVersion(14, 3)
  repository.addXcodeVersion(13, 4, 1)
  const needle = new SemanticVersionTemplate(16, SemanticVersionTemplatePlaceholder, SemanticVersionTemplatePlaceholder)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  await expect(matcher.findXcodeVersion(needle)).rejects.toThrow()
})

test("It throws when no version matches major and minor component", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(13, 1, 0)
  repository.addXcodeVersion(13, 2, 1)
  repository.addXcodeVersion(13, 3, 0)
  repository.addXcodeVersion(13, 3, 1)
  repository.addXcodeVersion(13, 4, 0)
  repository.addXcodeVersion(13, 4, 1)
  repository.addXcodeVersion(14, 0, 1)
  repository.addXcodeVersion(14, 0, 0)
  repository.addXcodeVersion(14, 1, 0)
  repository.addXcodeVersion(14, 2, 0)
  const needle = new SemanticVersionTemplate(14, 3, SemanticVersionTemplatePlaceholder)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  await expect(matcher.findXcodeVersion(needle)).rejects.toThrow()
})

test("It prefers release version of beta version", async () => {
  const repository = new MockXcodeVersionRepository()
  repository.addXcodeVersion(16, 4, 0)
  repository.addXcodeVersion(16, 4, 0, true)
  const needle = new SemanticVersionTemplate(16, SemanticVersionTemplatePlaceholder, SemanticVersionTemplatePlaceholder)
  const matcher = new XcodeVersionMatcher({ xcodeVersionRepository: repository })
  const xcodeVersion = await matcher.findXcodeVersion(needle)
  expect(xcodeVersion).not.toBeNull()
  expect(xcodeVersion?.version.major).toEqual(16)
  expect(xcodeVersion?.version.minor).toEqual(4)
  expect(xcodeVersion?.version.patch).toEqual(0)
  expect(xcodeVersion?.isBeta).toEqual(false)
  expect(xcodeVersion?.betaNumber).toBeNull()
})
