name: Install Enterprise Distribution Certificate
description: Installs the enterprise distribution certificate in the keychain.
author: Simon B. Støvring
runs:
  using: composite
  steps:
    - name: Install Enterprise Distribution Certificate
      run: |
        CERTIFICATE_PASSWORD=$(op read "op://GitHub Actions/Enterprise Distribution Certificate/password")
        CERTIFICATE_FILE_PATH=$(uuidgen).p12
        KEYCHAIN_PASSWORD=$(uuidgen)
        KEYCHAIN_NAME="signing_tmp.keychain"
        op read --out-file $CERTIFICATE_FILE_PATH "op://GitHub Actions/Enterprise Distribution Certificate/Certificate.p12"
        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        security import $CERTIFICATE_FILE_PATH -k "$KEYCHAIN_NAME" -f pkcs12 -A -T /usr/bin/codesign -T /usr/bin/security -P $CERTIFICATE_PASSWORD
        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
        security list-keychains -d user -s "$KEYCHAIN_NAME" "login.keychain"
        rm $CERTIFICATE_FILE_PATH
      shell: bash
