name: Install JFrog Artifactory profile
description: Installs the JFrog Artifactory CI profile credentials
author: Gerard Sala
runs:
  using: composite
  steps:
    - name: Install Artifactory profile
      run: |
        mkdir -p ~/.gradle
        echo "\n" >> ~/.gradle/gradle.properties
        echo "shape_consumer_username={{ op://25dt53lxtmov37u7s4b72weu3a/ofy7qo7ejdvdjxuopb4db3astu/username  }}" | op inject >> ~/.gradle/gradle.properties
        echo "shape_consumer_password={{ op://25dt53lxtmov37u7s4b72weu3a/ofy7qo7ejdvdjxuopb4db3astu/password  }}" | op inject >> ~/.gradle/gradle.properties
        echo "shapeArtifactoryUsername={{ op://25dt53lxtmov37u7s4b72weu3a/o3p3rrpz4lucyxmwb6mhke2s3e/username  }}" | op inject >> ~/.gradle/gradle.properties
        echo "shapeArtifactoryPassword={{ op://25dt53lxtmov37u7s4b72weu3a/o3p3rrpz4lucyxmwb6mhke2s3e/password  }}" | op inject >> ~/.gradle/gradle.properties
        mkdir -p ~/.m2
        cat templates/settings.template.xml | op inject > ~/.m2/settings.xml
      shell: bash
