name: Add comment to a Jira issue
description: Adds comments to a list of specified Jira issues by their specified ID's.
author: Mathias Mortensen
inputs:
  message:
    description: The message to post in the Jira comment
    required: true
  issues:
    description: Comma separated string of Jira issue ids. Example 'OK-1879,OK-1785,OK-1734'
    required: true
  jira-base-url:
    description: The URL to the Jira instance.
    required: true
    default: https://shapedk.atlassian.net
  jira-user-email:
    description: The Jira user who should post the comment. 
    required: true
    default: ci@shape.dk
  jira-api-token:
    description: Jira API token
    required: true
runs:
  using: composite
  steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-user-email }}
        JIRA_API_TOKEN: ${{ inputs.jira-api-token }}
    - name: Comment on issues
      uses: shapehq/gajira-comment@feature/multiple-issues
      with:
        issues: ${{ inputs.issues }}
        comment: ${{ inputs.message }}
