name: "Upload artifact to Firebase"
description: "Uploads an APK to Firebase App Distribution"
author: "Mikkel Schläger"

inputs:
  serviceCredentialsOpReference:
    description: "1Password reference to Google service account credentials json file (without quotes)"
    required: true

  appId:
    description: "Firebase App ID"
    required: true

  apkPath:
    description: "Path to the APK that will be uploaded"
    required: true

  releaseNotes:
    description: "Release notes for this distribution"
    required: false

  groups:
    description: "Comma separated list of Firebase tester group names"
    required: false

  testers:
    description: "Comma separated email list of testers to invite"
    required: false

outputs:
  firebase-console-uri:
    description: "Link to the release in the Firebase console"
    value: ${{ steps.distribute.outputs.firebase-console-uri }}

  testing-uri:
    description: "Link to the release in the Firebase App Tester app"
    value: ${{ steps.distribute.outputs.testing-uri }}

  binary-download-uri:
    description: "Link to the app binary (APK or AAB file). Expires after one hour."
    value: ${{ steps.distribute.outputs.binary-download-uri }}

  # Underscore variants for safe dot-notation access in workflows
  firebase_console_uri:
    description: "Link to the release in the Firebase console"
    value: ${{ steps.distribute.outputs.firebase_console_uri }}

  testing_uri:
    description: "Link to the release in the Firebase App Tester app"
    value: ${{ steps.distribute.outputs.testing_uri }}

  binary_download_uri:
    description: "Link to the app binary (APK or AAB file). Expires after one hour."
    value: ${{ steps.distribute.outputs.binary_download_uri }}

runs:
  using: composite
  steps:
    - name: "Install Firebase tools"
      shell: bash
      run: npm install -g firebase-tools

    - name: Load credentials
      uses: 1password/load-secrets-action@v2
      env:
        SERVICE_ACCOUNT_CREDENTIALS: ${{ inputs.serviceCredentialsOpReference }}

    - name: Write credentials file
      shell: bash
      run: |
        echo "$SERVICE_ACCOUNT_CREDENTIALS" > service-account.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=service-account.json" >> $GITHUB_ENV

    - name: "Distribute apk"
      id: distribute
      shell: bash
      env:
        APK_PATH: ${{ inputs.apkPath }}
        APP_ID: ${{ inputs.appId }}
        RELEASE_NOTES: ${{ inputs.releaseNotes }}
        TESTERS: ${{ inputs.testers }}
        GROUPS: ${{ inputs.groups }}
      run: |
        # Execute firebase command and process output line by line
        firebase appdistribution:distribute \
          "$APK_PATH" \
          --app "$APP_ID" \
          --release-notes "$RELEASE_NOTES" \
          --testers "$TESTERS" \
          --groups "$GROUPS" 2>&1 | while read -r line; do
          echo "$line"

          if [[ $line == *"View this release in the Firebase console"* ]]; then
            CONSOLE_URI=$(echo "$line" | sed -e 's/.*: //' -e 's/^ *//;s/ *$//')
            echo "firebase-console-uri=$CONSOLE_URI" >> "$GITHUB_OUTPUT"
            echo "firebase_console_uri=$CONSOLE_URI" >> "$GITHUB_OUTPUT"
          elif [[ $line == *"Share this release with testers who have access"* ]]; then
            TESTING_URI=$(echo "$line" | sed -e 's/.*: //' -e 's/^ *//;s/ *$//')
            echo "testing-uri=$TESTING_URI" >> "$GITHUB_OUTPUT"
            echo "testing_uri=$TESTING_URI" >> "$GITHUB_OUTPUT"
          elif [[ $line == *"Download the release binary"* ]]; then
            BINARY_URI=$(echo "$line" | sed -e 's/.*: //' -e 's/^ *//;s/ *$//')
            echo "binary-download-uri=$BINARY_URI" >> "$GITHUB_OUTPUT"
            echo "binary_download_uri=$BINARY_URI" >> "$GITHUB_OUTPUT"
          fi
        done
