name: "Upload artifact to Firebase"
description: "Uploads an APK to Firebase App Distribution"
author: "Mikkel Schläger"

inputs:
  tokenOpReference:
    description: "1Password reference to Firebase CLI access token"
    required: true

  appId:
    description: "Firebase App ID"
    required: true

  apkPath:
    description: "Path to the APK that will be uploaded"
    required: true

  releaseNotes:
    description: "Release notes for this build"
    required: false

runs:
  using: composite
  steps:
    - name: "Install Firebase tools"
      shell: bash
      run: npm install -g firebase-tools

    - name: "Read Firebase access token"
      shell: bash
      run: FIREBASE_TOKEN=$(op read "op://REMA 1000 GitHub Actions/Firebase access token/password")

    - name: "Distribute apk"
      shell: bash

      env:
        APK_PATH: ${{ inputs.apkPath }}
        APP_ID: ${{ inputs.appId }}
        RELEASE_NOTES: ${{ inputs.releaseNotes }}

      run: |
        firebase appdistribution:distribute "$APK_PATH" \
        --app "$APP_ID" \
        --release-notes "$RELEASE_NOTES"
