name: "Upload artifact to Firebase"
description: "Uploads an APK to Firebase App Distribution"
author: "Mikkel Schläger"

inputs:
  serviceCredentialsOpReference:
    description: "1Password reference to Google service account credentials json file (without quotes)"
    required: true

  appId:
    description: "Firebase App ID"
    required: true

  apkPath:
    description: "Path to the APK that will be uploaded"
    required: true

  releaseNotes:
    description: "Release notes for this distribution"
    required: false

  groups:
    description: "Comma separated list of Firebase tester group names"
    required: false

  testers:
    description: "Comma separated email list of testers to invite"
    required: false

runs:
  using: composite
  steps:
    - name: "Install Firebase tools"
      shell: bash
      run: npm install -g firebase-tools

    - name: "Distribute apk"
      shell: bash

      env:
        APK_PATH: ${{ inputs.apkPath }}
        APP_ID: ${{ inputs.appId }}
        RELEASE_NOTES: ${{ inputs.releaseNotes }}
        TESTERS: ${{ inputs.testers }}
        GROUPS: ${{ inputs.groups }}

      run: |
        op read "${{ inputs.serviceCredentialsOpReference }}" -o credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=$(realpath credentials.json)
        firebase appdistribution:distribute \
        "$APK_PATH" \
        --app "$APP_ID" \
        --release-notes "$RELEASE_NOTES" \
        --testers "TESTERS" \
        --groups "GROUPS"
