name: Install the CI SSH Key
description: Installs the CI server's SSH key
author: Simon B. Støvring
inputs:
  filename:
    description: Name of the file to store the key in.
    required: false
    default: id_rsa
runs:
  using: composite
  steps:
    - name: Load CI SSH Key
      id: ci-ssh-key
      uses: 1password/load-secrets-action@v3
      env:
        CI_SSH_KEY: op://GitHub Actions/CI SSH Private Key/ci-ssh-key
    - name: Install CI SSH Key
      uses: shapehq/actions/install-ssh-key@v1
      with:
        ssh-key: ${{ steps.ci-ssh-key.outputs.CI_SSH_KEY }}
        filename: ${{ inputs.filename }}
