name: Install the CI SSH Key
description: Installs the CI server's SSH key
author: Simon B. Støvring
inputs:
  filename:
    description: Name of the file to store the key in.
    required: false
    default: id_rsa
runs:
  using: composite
  steps:
    - name: Install CI SSH Key
      run: |
        mkdir -p ~/.ssh
        op read --out-file ~/.ssh/${{ inputs.filename }} "op://GitHub Actions/CI SSH Private Key/ci-ssh-key"
        ssh-add ~/.ssh/${{ inputs.filename }}
      shell: bash
