name: Install the CI SSH Key
description: Installs the CI server's SSH key
author: Simon B. Støvring
inputs:
  filename:
    description: Name of the file to store the key in.
    required: false
    default: id_rsa
runs:
  using: composite
  steps:
    - name: Install CI SSH Key
      uses: shapehq/actions/install-ssh-key@main
      with:
        op-reference: op://GitHub Actions/CI SSH Private Key/ci-ssh-key
        filename: ${{ inputs.filename }}
