name: Post Loco Translation Status
inputs:
  channel:
    description: Slack channel to post message in
    required: true  
  slack-token:
    description: Slack access token
    required: true
  loco-api-key:
    description: Loco api key
    required: true
runs:
  using: composite
  steps:
    - name: Post Status
      run: |
        job_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        cd "${{ github.action_path }}/LocoTranslationStatusPoster"
        swift run LocoTranslationStatusPoster --channel "${{ inputs.channel }}" --token "${{ inputs.slack-token }}" --loco-api-key "${{ inputs.loco-api-key }}" --workflow "${{ github.workflow }}" --started-by "${{ github.actor }}" --job-url "${job_url}"
      shell: bash
