name: Installs App Store Connect API Key
inputs:
  op-asc-key-issuer-id-reference:
    required: true
  op-asc-key-id-reference:
    required: true
  op-asc-key-file-reference:
    required: true
  output-asc-key-file-directory:
    required: false
    default: .
outputs:
  issuer-id:
    value: ${{ steps.read.outputs.issuer_id }}
  key-id:
    value: ${{ steps.read.outputs.key_id }}
runs:
  using: composite
  steps:
    - id: read
      run: |
        # Read issuer id
        issuer_id=$(op read "${{ inputs.op-asc-key-issuer-id-reference }}")
        echo "issuer_id=${issuer_id}" >> $GITHUB_OUTPUT

        # Read key id
        key_id=$(op read "${{ inputs.op-asc-key-id-reference }}")
        echo "key_id=${key_id}" >> $GITHUB_OUTPUT
        
        # Ensure output directory exists
        mkdir -p "${{ output-asc-key-file-directory }}"

        # Read key file
        key_filename="AuthKey_${key_id}.p8"
        key_file_path="${{ output-asc-key-file-directory }}/${key_filename}"
        op read --out-file "${key_file_path}" "${{ op-asc-key-file-reference }}"
        echo "key_filename=${key_filename}" >> $GITHUB_OUTPUT
        echo "key_file_path=${key_file_path}" >> $GITHUB_OUTPUT
      shell: bash