name: Check Loco Translation Status
inputs:
  loco-api-key:
    description: Loco api key
    required: true
runs:
  using: composite
  steps:
    - name: Check Status
      run: |
        cd "${{ github.action_path }}/LocoTranslationStatusChecker"
        swift run LocoTranslationStatusChecker --loco-api-key "${{ inputs.loco-api-key }}"
      shell: bash
