name: Install Provisioning Profile with 1Password
description: Installs a provisioning profile read from 1Password
author: Simon B. Støvring
inputs:
  op-reference:
    description: Reference to the item in 1Password.
    required: true
runs:
  using: composite
  steps:
    - name: Install Provisioning Profile
      run: |
        PROVISIONING_PROFILE_DIR=~/Library/MobileDevice/Provisioning\ Profiles
        PROVISIONING_PROFILE_FILE_PATH=$PROVISIONING_PROFILE_DIR/$(uuidgen).mobileprovision
        mkdir -p "${PROVISIONING_PROFILE_DIR}"
        op read --out-file "${PROVISIONING_PROFILE_FILE_PATH}" "${{ inputs.op-reference }}"
      shell: bash
