name: Install Shipshape
description: Installs Shipshape and sets an activation code.
author: Simon B. Støvring
inputs:
  activation-code:
    description: Activation code for Shipshape.
    required: true
runs:
  using: composite
  steps:
    - name: Install Shipshape
      run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
      shell: bash
    - name: Setup Shipshape Activation Code
      run: |
        set -euo pipefail
        SHIPSHAPE_ACTIVATION_CODE="${{ inputs.activation-code }}"
        if [ -z "$SHIPSHAPE_ACTIVATION_CODE" ]; then
          echo "Error: activation-code cannot be empty."
          exit 1
        fi
        echo '{"ship_activation_code":"'${SHIPSHAPE_ACTIVATION_CODE}'"}' > ~/shape-dev.config
      shell: bash
