name: Select Xcode Versions
description: Selects a version of Xcode.
branding:
  icon: smartphone
  color: blue
inputs:
  version:
    description: The version of Xcode to install.
    required: true
runs:
  using: node20
  main: dist/index.js
