name: Select Xcode Version
description: Selects a version of Xcode.
author: Simon B. Støvring
inputs:
  version:
    description: Version of Xcode to select.
    required: true
runs:
  using: composite
  steps:
    - name: Select Xcode Version
      run: |
        APPLICATIONS_DIR=/Applications
        XCODE_VERSION=$(echo "${{ inputs.version }}" | xargs | sed "s/ /_/g")
        XCODE_PATH="$APPLICATIONS_DIR/Xcode_${XCODE_VERSION}.app"
        if [ -d "$XCODE_PATH" ]; then
          sudo xcode-select -s $XCODE_PATH/Contents/Developer
        else
          echo "Xcode ${XCODE_VERSION} was not found. The following versions of Xcode are available:"
          ls "${APPLICATIONS_DIR}" \
            | grep '^Xcode_' \
            | sed -e "s/^Xcode_//" -e "s/.app$//" -e "s/^/- /" -e "s/_/ /g"
          exit 1
        fi
      shell: bash
