name: Vibeke
description: Vibe code a pull request
author: Simon B. Støvring
inputs:
  anthropic-api-key-op-reference:
    description: Reference to an Anthropic API key in 1Password.
    required: true
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "vibeke-by-framna"
        git config user.email "vibeke@dk.framna.com"
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1
    - name: Check PR Comment
      id: check-pr-comment
      shell: bash
      if: |
          (
            github.event_name == 'issue_comment' &&
            contains(github.event.comment.body, '@vibeke-by-framna') &&
            github.event.comment.user.login != 'vibeke-by-framna'
          ) || (
            github.event_name == 'pull_request_review_comment' &&
            contains(github.event.comment.body, '@vibeke-by-framna') &&
            github.event.comment.user.login != 'vibeke-by-framna'
          ) || (
            github.event_name == 'pull_request_review' &&
            contains(github.event.review.body, '@vibeke-by-framna') &&
            github.event.review.user.login != 'vibeke-by-framna'
          )
      run: echo "is-pr-comment=true" >> $GITHUB_OUTPUT
    - name: Read Anthropic API Key
      id: anthropic-api-key
      shell: bash
      run: |
        api_key=$(op read "${{ inputs.anthropic-api-key-op-reference }}")
        echo "api-key=${api_key}" >> $GITHUB_OUTPUT
    - name: Config
      id: config
      shell: bash
      run: |
        vibeke_service_url="https://smooth-daily-goshawk.ngrok-free.app"
        allowed_tools="WebFetch,WebSearch,Edit,MultiEdit,Write,Bash,mcp__github__create_pull_request,mcp__github__list_pull_requests,mcp__github__get_pull_request_files,mcp__github__get_pull_request_status,mcp__github__update_pull_request_branch,mcp__github__get_pull_request_comments,mcp__github__get_pull_request_reviews,mcp__github__get_pull_request_diff,mcp__github__create_pull_request,mcp__github__update_pull_request,mcp__github__create_or_update_file,mcp__github__delete_file,mcp__github__list_branches,mcp__github__push_files,mcp__github__get_file_contents,mcp__github__create_branch,mcp__github__list_commits,mcp__github__get_commit,mcp__github__get_tag,mcp__github__list_tags,mcp__github__search_code"
        echo "vibeke-service-url=${vibeke_service_url}" >> $GITHUB_OUTPUT
        echo "allowed-tools=${allowed_tools}" >> $GITHUB_OUTPUT
    - name: Exchange GitHub Token for Installation Token
      id: exchange-github-token
      shell: bash
      if: ${{ steps.check-pr-comment.outputs.is-pr-comment == 'true' }}
      run: |
        RESPONSE=$(curl -s -X POST "${{ steps.config.outputs.vibeke-service-url }}/api/v1/installation-token" \
          -H "Content-Type: application/json" \
          -d "{\"token\":\"${{ github.token }}\",\"repository\":\"${{ github.repository }}\"}")
        INSTALLATION_TOKEN=$(echo "$RESPONSE" | jq -r '.installationToken // empty')
        if [ -n "$INSTALLATION_TOKEN" ]; then
          echo "installation-token=${INSTALLATION_TOKEN}" >> $GITHUB_OUTPUT
        else
          echo "Failed to retrieve installation token. Response:"
          echo "$RESPONSE"
          exit 1
        fi
    - name: Playground
      shell: bash
      run: |
        RESPONSE=$(curl -v "https://api.github.com/repos/${{ github.repository }}" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "Accept: application/vnd.github+json")
        echo $RESPONSE
    # - name: Claude Code
    #   uses: anthropics/claude-code-base-action@v0.0.26
    #   if: github.event_name == 'repository_dispatch' && github.event.action == 'vibeke_create_pr'
    #   id: claude-code-create-pr
    #   env:
    #     GITHUB_TOKEN: ${{ github.event.client_payload.installation_token }}
    #   with:
    #     anthropic_api_key: ${{ steps.anthropic-api-key.outputs.api-key }}
    #     model: ${{ github.event.client_payload.model }}
    #     prompt: ${{ github.event.client_payload.prompt }}
    #     timeout_minutes: 60
    #     allowed_tools: ${{ steps.config.outputs.allowed-tools }}
    # - name: Claude Code
    #   uses: anthropics/claude-code-action@beta
    #   if: ${{ steps.check-pr-comment.outputs.is-pr-comment == 'true' }}
    #   id: claude-code-update-pr
    #   with:
    #     anthropic_api_key: ${{ steps.anthropic-api-key.outputs.api-key }}
    #     timeout_minutes: 60
    #     allowed_tools: ${{ steps.config.outputs.allowed-tools }}
    #     trigger_phrase: "@vibeke-by-framna"
    #     github_token: ${{ steps.exchange-github-token.outputs.installation-token }}
    # - name: Display Claude Code Report
    #   if: ${{ steps.claude-code-create-pr.outputs.execution_file != '' || steps.claude-code-update-pr.outputs.execution_file != '' }}
    #   shell: bash
    #   run: |
    #     echo "## Claude Code Report" >> $GITHUB_STEP_SUMMARY
    #     echo '```json' >> $GITHUB_STEP_SUMMARY
    #     if [[ -n "${{ steps.claude-code-create-pr.outputs.execution_file }}" ]]; then
    #       cat "${{ steps.claude-code-create-pr.outputs.execution_file }}" >> $GITHUB_STEP_SUMMARY
    #     else
    #       cat "${{ steps.claude-code-update-pr.outputs.execution_file }}" >> $GITHUB_STEP_SUMMARY
    #     fi
    #     echo '```' >> $GITHUB_STEP_SUMMARY
    # - name: Revoke Installation Tokens
    #   shell: bash
    #   run: |
    #     delete_token() {
    #       local token="$1"
    #       if [[ -n "$token" ]]; then
    #         curl -sSL -X DELETE \
    #           -H "Content-Type: application/json" \
    #           -d "{\"installationToken\":\"${token}\"}" \
    #           "${{ steps.config.outputs.vibeke-service-url }}/api/v1/installation-token"
    #       fi
    #     }
    #     delete_token "${{ github.event.client_payload.installation_token }}"
    #     delete_token "${{ steps.exchange-github-token.outputs.installation-token }}"
