name: Prepare Apple Environment
description: Prepares the environment to be used for distributing apps on Apple's platforms.
author: Simon B. Støvring
runs:
  using: composite
  steps:
    - name: Load SSH Key from 1Password
      id: op-ssh-key
      uses: 1password/load-secrets-action@v1
      env:
        SECRET: op://GitHub Actions/CI SSH Private Key/ci-ssh-key
    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        op read --out-file ~/.ssh/id_rsa ${{ steps.op-ssh-key.outputs.SECRET }}
      shell: bash
    - name: Install Shipshape
      run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
      shell: bash
    # - name: Setup Shipshape Activation Code
    #   run: |
    #     SHIPSHAPE_ACTIVATION_CODE=$(op read "op://GitHub Actions/CI Shipshape Activation Code/password")
    #     echo '{"ship_activation_code":"${SHIPSHAPE_ACTIVATION_CODE}"}' > ~/shape-dev.config
    #   shell: bash
    # - name: Install appiconannotator
    #   run: npm install -g git+ssh://git@github.com:shapehq/appiconannotator
    #   shell: bash
    # - name: Set Up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 3.1.2
    #     bundler-cache: true
    # - name: Install Enterprise Distribution Certificate
    #   run: |
    #     CERTIFICATE_PASSWORD=$(op read "op://GitHub Actions/Enterprise Distribution Certificate/password")
    #     CERTIFICATE_FILE_PATH=$(uuidgen).p12
    #     op read --out-file $CERTIFICATE_FILE_PATH "op://GitHub Actions/Enterprise Distribution Certificate/Certificate.p12"
    #     security import $CERTIFICATE_FILE_PATH -P $CERTIFICATE_PASSWORD
    #     rm $CERTIFICATE_FILE_PATH
    #   shell: bash
    # - name: Install Enterprise Distribution Provisioning Profile
    #   run: |
    #     PROVISIONING_PROFILE_DIR=~/Library/MobileDevice/Provisioning\ Profiles
    #     PROVISIONING_PROFILE_FILE_PATH=$PROVISIONING_PROFILE_DIR/$(uuidgen).mobileprovision
    #     mkdir -p "${PROVISIONING_PROFILE_DIR}"
    #     op read --out-file "${PROVISIONING_PROFILE_FILE_PATH}" "op://GitHub Actions/Enterprise Distribution Provisioning Profile/profile.mobileprovision"
    #   shell: bash
