name: Prepare Apple Environment
description: Prepares the environment to be used for distributing apps on Apple's platforms.
author: Simon B. Støvring
inputs: 
  ci-ssh-key:
    required: true
  ci-ssh-known-hosts:
    required: true
  shipshape-activation-code:
    required: true
  distribution-certificate-base64:
    required: true
  distribution-certificate-password:
    required: true
  
runs:
  using: composite
  steps:
    - name: Install SSH Key
      uses: benoitchantre/setup-ssh-authentication-action@1.0.0
      with:
        private-key: ${{ inputs.ci-ssh-key }}
        known-hosts: ${{ inputs.ci-ssh-known-hosts }}
    - name: Install Shipshape
      run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
      shell: bash
    - name: Setup Shipshape Activation Code
      run: echo '{"ship_activation_code":"${{ inputs.shipshape-activation-code }}"}' > ~/shape-dev.config
      shell: bash
    - name: Install appiconannotator
      run: npm install -g git+ssh://git@github.com:shapehq/appiconannotator
      shell: bash
    - name: Set Up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
    - name: Install Certificate
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ inputs.distribution-certificate-base64 }}
        p12-password: ${{ inputs.distribution-certificate-password }}
