name: Prepare Apple Environment
description: Prepares the environment to be used for distributing apps on Apple's platforms.
author: Simon B. Støvring
runs:
  using: composite
  steps:
    - name: Load SSH Key from 1Password
      id: op-ssh-key
      uses: 1password/load-secrets-action@v1.1.0
      env:
        SECRET: op://GitHub Actions/CI SSH Private Key/ci-ssh-key
        OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ steps.op-ssh-key.outputs.SECRET }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
      shell: bash
    - name: Install Shipshape
      run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
      shell: bash
    - name: Load Shipshape Activation Code from 1Password
      id: op-shipshape-activation-code
      uses: 1password/load-secrets-action@v1.1.0
      env:
        SECRET: op://GitHub Actions/CI Shipshape Activation Code/password
        OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
    - name: Setup Shipshape Activation Code
      run: |
        echo '{"ship_activation_code":"${{ steps.op-shipshape-activation-code.outputs.SECRET }}"}' > ~/shape-dev.config
      shell: bash
    - name: Install appiconannotator
      run: npm install -g git+ssh://git@github.com:shapehq/appiconannotator
      shell: bash
    - name: Set Up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
    - name: Load Password for Enterprise Distribution Certificate from 1Password
      id: op-certificate-password
      uses: 1password/load-secrets-action@v1.1.0
      env:
        SECRET: op://GitHub Actions/Enterprise Distribution Certificate/password
        OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
    - name: Load Enterprise Distribution Certificate from 1Password
      id: op-certificate
      uses: 1password/load-secrets-action@v1.1.0
      env:
        SECRET: op://GitHub Actions/Enterprise Distribution Certificate/Certificate.p12
        OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}
    - name: Install Enterprise Distribution Certificate
      run: |
        CERTIFICATE_FILE_PATH=$(uuidgen).p12
        echo ${{ steps.op-certificate.outputs.SECRET }}} > $CERTIFICATE_FILE_PATH
        op read --out-file $CERTIFICATE_FILE_PATH "
        security import $CERTIFICATE_FILE_PATH -P ${{ steps.op-certificate-password.outputs.SECRET }}}
        rm $CERTIFICATE_FILE_PATH
    #   shell: bash
    # - name: Install Enterprise Distribution Provisioning Profile
    #   run: |
    #     PROVISIONING_PROFILE_DIR=~/Library/MobileDevice/Provisioning\ Profiles
    #     PROVISIONING_PROFILE_FILE_PATH=$PROVISIONING_PROFILE_DIR/$(uuidgen).mobileprovision
    #     mkdir -p "${PROVISIONING_PROFILE_DIR}"
    #     op read --out-file "${PROVISIONING_PROFILE_FILE_PATH}" "op://GitHub Actions/Enterprise Distribution Provisioning Profile/profile.mobileprovision"
    #   shell: bash
