name: Prepare Apple Environment
description: Prepares the environment to be used for distributing apps on Apple's platforms.
author: Simon B. Støvring
runs:
  using: composite
  steps:
    - name: Install SSH Key
      uses: benoitchantre/setup-ssh-authentication-action@1.0.0
      with:
        private-key: ${{ secrets.CI_SSH_KEY }}
        known-hosts: ${{ secrets.CI_SSH_KNOWN_HOSTS }}
    - name: Install Shipshape
      run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
      shell: bash
    - name: Setup Shipshape Activation Code
      run: echo '{"ship_activation_code":"c6a40d"}' > ~/shape-dev.config
      shell: bash
    - name: Install appiconannotator
      run: npm install -g git+ssh://git@github.com:shapehq/appiconannotator
      shell: bash
    - name: Set Up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
