name: Prepare Apple Environment
description: Prepares the environment to be used for distributing apps on Apple's platforms.
author: Simon B. Støvring
inputs:
  secrets:
    required: true
runs:
  using: composite
  steps:
    - name: Install SSH Key
      uses: benoitchantre/setup-ssh-authentication-action@1.0.0
      with:
        private-key: ${{ fromJSON(inputs.secrets).CI_SSH_KEY }}
        known-hosts: ${{ fromJSON(inputs.secrets).CI_SSH_KNOWN_HOSTS }}
    - name: Install Shipshape
      run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
      shell: bash
    - name: Setup Shipshape Activation Code
      run: echo '{"ship_activation_code":"${{ fromJSON(inputs.secrets).SHIPSHAPE_ACTIVATION_CODE }}"}' > ~/shape-dev.config
      shell: bash
    - name: Install appiconannotator
      run: npm install -g git+ssh://git@github.com:shapehq/appiconannotator
      shell: bash
    - name: Set Up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
    - name: Install Certificate
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ fromJSON(inputs.secrets).APPLE_ENTERPRISE_DISTRIBUTION_CERTIFICATE }}
        p12-password: ${{ fromJSON(inputs.secrets).APPLE_ENTERPRISE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
    - name: Checkout Actions Repository
      uses: actions/checkout@v3
      with:
        repository: shapehq/actions
        path: ./.actions
        ssh-key: ${{ fromJSON(inputs.secrets).CI_SSH_KEY }}
    - name: Install 1Password CLI
      uses: ./.actions/install-op-cli
    - name: Install Enterprise Provisioning Profile
      uses: ./.actions/install-provisioning-profile
      with:
        profile-base64: ${{ fromJSON(inputs.secrets).APPLE_ENTERPRISE_PROVISIONING_PROFILE }}
