name: Prepare Apple Environment
description: Prepares the environment to be used for distributing apps on Apple's platforms.
author: Simon B. Støvring
inputs:
  secrets:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3
      with:
        repository: shapehq/actions
        ref: feature/install-op-cli
        path: ./.actions
        ssh-key: ${{ fromJSON(inputs.secrets).CI_SSH_KEY }}
    - name: Install 1Password CLI
      uses: ./.actions/install-op-cli
    # - name: Install SSH Key
    #   run: |
    #     mkdir -p ~/.ssh
    #     op read --out-file ~/.ssh/id_rsa "op://GitHub Actions/CI SSH Private Key/ci-ssh-key"
    #   shell: bash
    # - name: Install Shipshape
    #   run: npm install -g git+ssh://git@github.com:shapehq/ship-shape-cli.git
    #   shell: bash
    # - name: Setup Shipshape Activation Code
    #   run: |
    #     SHIPSHAPE_ACTIVATION_CODE=$(op read "op://GitHub Actions/CI Shipshape Activation Code/password")
    #     echo '{"ship_activation_code":"${SHIPSHAPE_ACTIVATION_CODE}"}' > ~/shape-dev.config
    #   shell: bash
    # - name: Install appiconannotator
    #   run: npm install -g git+ssh://git@github.com:shapehq/appiconannotator
    #   shell: bash
    # - name: Set Up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 3.1.2
    #     bundler-cache: true
    - name: Install Enterprise Distribution Certificate
      run: |
        CERTIFICATE_PASSWORD=$(op read "op://GitHub Actions/Enterprise Distribution Certificate/password")
        CERTIFICATE_FILE_PATH=enterprise_distribution_certificate.p12
        op read --out-file $CERTIFICATE_FILE_PATH "op://GitHub Actions/Enterprise Distribution Certificate/Certificate.p12"
        security import $CERTIFICATE_FILE_PATH -P $CERTIFICATE_PASSWORD
        rm $CERTIFICATE_FILE_PATH
    # - name: Install Enterprise Provisioning Profile
    #   uses: ./.actions/install-provisioning-profile
    #   with:
    #     profile-base64: ${{ fromJSON(inputs.secrets).APPLE_ENTERPRISE_PROVISIONING_PROFILE }}
