name: Build and Upload to App Store Connect
inputs:
  working-directory:
    description: The directory to run the action in. This should be the directory in which the Xcode project resides.
    default: .
    required: true
  scheme:
    description: The Xcode project's scheme to build. This specifies which set of build settings and targets to use when building your app.
    required: true
  configuration:
    description: Specifies the build configuration that Xcode should use. Commonly set to "Release" for production builds meant for App Store distribution.
    default: Release
    required: true
  marketing-version:
    description: The marketing version number of the app, such as "1.0.0". This sets the MARKETING_VERSION in Xcode, determining the version displayed on the App Store.
    required: false
  build-number:
    description: An incrementing number specifying the build version, which is used to uniquely identify an archive or build sent to the App Store Connect.
    required: false
  testflight-internal-testing-only:
    description: When enabled, the build cannot be distributed via external TestFlight or the App Store. Must be either "true" or "false".
    default: false
    required: true
  app-store-connect-api-key-issuer-id:
    description: Issuer ID for the App Store Connect API key.
    required: true
  app-store-connect-api-key-id:
    description: App Store Connect API Key ID.
    required: true
  app-store-connect-api-key-base64:
    description: Base64-encoded AuthKey.p8 file.
    required: false
  app-store-connect-api-key-file:
    description: Path to an AuthKey.p8 file.
    required: false
  development-certificate-base64:
    description: Base64-encoded development certificate (.p12).
    required: false
  development-certificate-file:
    description: Path to a development certificate (.p12).
    required: false
  development-certificate-password:
    description: Password for decrypting the development certificate (.p12 file).
    required: true
  additional-archive-args:
    description: Additional arguments passed to xcodebuild when archiving the app.
    required: false
  build-directory:
    description: Defines the directory where the build artifacts, like the final binary or intermediate files, will be stored.
    default: .build
    required: true
  dsyms-archive-name:
    description: Name of the uploaded archive containing the dSYMs.
    default: dSYMs
    required: true
  pretty-xcodebuild-output:
    description: Whether to pipe xcodebuild output through xcbeautify for prettier formatting.
    default: true
    required: true
  additional-altool-args:
    description: Additional arguments passed to altool when uploading the app.
    required: false
runs:
  using: composite
  steps:
    - name: Install App Store Connect API Key
      id: install-app-store-connect-api-key
      uses: shapehq/actions/install-asc-api-key@v1
      with:
        asc-key-issuer-id: ${{ inputs.app-store-connect-api-key-issuer-id }}
        asc-key-id: ${{ inputs.app-store-connect-api-key-id }}
        asc-key-base64: ${{ inputs.app-store-connect-api-key-base64 }}
        asc-key-file: ${{ inputs.app-store-connect-api-key-file }}
        output-asc-key-file-directory: ~/.private_keys
    - name: Install Development Certificate
      uses: shapehq/actions/install-certificate@v1
      with:
        certificate-password: ${{ inputs.development-certificate-password }}
        certificate-base64: ${{ inputs.development-certificate-base64 }}
        certificate-file: ${{ inputs.development-certificate-file }}
    - name: Create Export Options Plist
      id: create-export-options-plist
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        # Create Export Options Plist
        if [[ "${{ inputs.testflight-internal-testing-only }}" != "true" && "${{ inputs.testflight-internal-testing-only }}" != "false" ]]; then
          echo "Error: testflight-internal-testing-only must be 'true' or 'false'"
          exit 1
        fi
        mkdir -p ${{ inputs.build-directory }}
        FILE_PATH="${{ inputs.build-directory }}/export-options.plist"
        cat <<EOL > $FILE_PATH
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>signingStyle</key>
          <string>automatic</string>
          <key>method</key>
          <string>app-store-connect</string>
          <key>destination</key>
          <string>export</string>
          <key>testFlightInternalTestingOnly</key>
          <${{ inputs.testflight-internal-testing-only }}/>
        </dict>
        </plist>
        EOL
        echo "file-path=${FILE_PATH}" >> "$GITHUB_OUTPUT"
    - name: Set Build Number
      shell: bash
      if: "${{ inputs.build-number != '' }}"
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Set Build Number
        xcrun agvtool new-version -all ${{ inputs.build-number }}
    - name: Archive App
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Archive App
        archive_app() {
          local cmd_args=""
          if [ -n "${{ inputs.marketing-version }}" ]; then
            cmd_args="$cmd_args MARKETING_VERSION=${{ inputs.marketing-version }}"
          fi
          if [ -n "${{ inputs.additional-archive-args }}" ]; then
            cmd_args="$cmd_args ${{ inputs.additional-archive-args }}"
          fi
          xcodebuild archive\
            -scheme ${{ inputs.scheme }}\
            -destination generic/platform=ios\
            -configuration ${{ inputs.configuration }}\
            -archivePath ${{ inputs.scheme }}.xcarchive\
            -skipPackagePluginValidation\
            -allowProvisioningUpdates\
            -authenticationKeyIssuerID ${{ steps.install-app-store-connect-api-key.outputs.issuer-id }}\
            -authenticationKeyID ${{ steps.install-app-store-connect-api-key.outputs.key-id }}\
            -authenticationKeyPath ${{ steps.install-app-store-connect-api-key.outputs.key-file-path }} $cmd_args
        }
        if [[ "${{ inputs.pretty-xcodebuild-output }}" == "true" ]]; then
          set -o pipefail && archive_app 2>&1 | xcbeautify --renderer github-actions
        else
          archive_app
        fi
    - name: Export IPA from Archive
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Export IPA from Archive
        export_ipa() {
          xcodebuild -exportArchive\
            -archivePath "${{ inputs.scheme }}.xcarchive"\
            -exportPath ${{ inputs.build-directory }}\
            -exportOptionsPlist "${{ steps.create-export-options-plist.outputs.file-path }}"\
            -allowProvisioningUpdates\
            -authenticationKeyIssuerID ${{ steps.install-app-store-connect-api-key.outputs.issuer-id }}\
            -authenticationKeyID ${{ steps.install-app-store-connect-api-key.outputs.key-id }}\
            -authenticationKeyPath ${{ steps.install-app-store-connect-api-key.outputs.key-file-path }}
        }
        if [[ "${{ inputs.pretty-xcodebuild-output }}" == "true" ]]; then
          set -o pipefail && export_ipa 2>&1 | xcbeautify --renderer github-actions
        else
          export_ipa
        fi
    - name: Archive the dSYMs
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.dsyms-archive-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.scheme }}.xcarchive/dSYMs/*
        if-no-files-found: error
    - name: Find IPA
      id: find-ipa
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Find IPA
        IPA_FILE_PATH=$(find "${{ inputs.build-directory }}" -type f -name "*.ipa" | head -n 1)
        if [ -n "$IPA_FILE_PATH" ]; then
          echo "file-path=${IPA_FILE_PATH}" >> "$GITHUB_OUTPUT"
        else
          echo "::error title=IPA not found::No file with the .ipa extension was found in the ${{ inputs.build-directory }} folder"
          exit 1
        fi
    - name: Upload IPA to App Store Connect
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        # Build the command as an array
        cmd=(xcrun altool
          --upload-app
          -t ios
          -f "${{ steps.find-ipa.outputs.file-path }}"
          --apiKey "${{ steps.install-app-store-connect-api-key.outputs.key-id }}"
          --apiIssuer "${{ steps.install-app-store-connect-api-key.outputs.issuer-id }}"
        )

        # Only append if input is non-empty. Tokenize respecting quotes.
        if [[ -n "${{ inputs.additional-altool-args }}" ]]; then
          read -r -a extra <<< "${{ inputs.additional-altool-args }}"
          cmd+=("${extra[@]}")
        fi

        "${cmd[@]}"
