name: Upload APK to ShipShape
description: Uploads an APK to our internal app distribution system
author: Gerard Sala
inputs:
  projectName:
    description: "Project name"
    required: true
  targetName:
    description: "Target name"
    required: true
  apkPath:
    description: "Path to the APK that will be uploaded"
    required: true
  manifestPath:
    description: "Path to the app's AndroidManifest.xml"
    required: true
  appIconPath:
    description: "Path to the app icon"
    required: true
  distributionListDefinitions:
    description: 'Distribution lists containing all available options. Expects a JSON e.g. { "List1" : ["Email1", "Email2"], "List2" : ["Email1", "Email2"] }'
    required: true
  distributionListTargets:
    description: 'Distribution lists that will get access to this upload. Expects comma-separated values e.g. "List1,List2"'
  releaseNotes:
    description: "Release notes"
    required: false
  sendEmail:
    type: boolean
    description: 'Send Email'
    default: false
    required: false
  sendPush:
    type: boolean
    description: 'Send Push'
    default: false
    required: false
  ssh-key:
    description: SSH private key contents for Shipshape access.
    required: false
  ssh-key-base64:
    description: Base64-encoded SSH private key.
    required: false
  ssh-key-file:
    description: Path to an SSH private key file.
    required: false
  ssh-key-password:
    description: Password for the SSH key.
    required: false
  shipshape-activation-code:
    description: Activation code for Shipshape.
    required: true

runs:
  using: composite
  steps:
    - name: Install SSH Key
      uses: shapehq/actions/install-ssh-key@v1
      with:
        ssh-key: ${{ inputs.ssh-key }}
        ssh-key-base64: ${{ inputs.ssh-key-base64 }}
        ssh-key-file: ${{ inputs.ssh-key-file }}
        ssh-key-password: ${{ inputs.ssh-key-password }}

    - name: Install Shipshape
      uses: shapehq/actions/install-shipshape@v1
      with:
        activation-code: ${{ inputs.shipshape-activation-code }}

    - name: Create shape-app.config
      shell: bash
      env:
        PROJECT_NAME: ${{ inputs.projectName }}
        TARGET_NAME: ${{ inputs.targetName }}
        APK_PATH: ${{ inputs.apkPath }}
        MANIFEST_PATH: ${{ inputs.manifestPath }}
        DISTRIBUTION_LIST_DEFINITIONS: ${{ inputs.distributionListDefinitions }}
      run: |
        jq -n \
          --arg project_name "$PROJECT_NAME" \
          --arg target_name "$TARGET_NAME" \
          --arg android_apk_path "$APK_PATH" \
          --arg android_manifest_path "$MANIFEST_PATH" \
          --argjson ship_shape_distribution_lists "$DISTRIBUTION_LIST_DEFINITIONS" \
          '{
            project_name: $project_name,
            target_name: $target_name,
            android_apk_path: $android_apk_path,
            android_manifest_path: $android_manifest_path,
            ship_shape_distribution_lists: $ship_shape_distribution_lists
          }' > shape-app.config

    - name: Create release_notes.txt
      shell: bash
      env:
        RELEASE_NOTES: ${{ inputs.releaseNotes || '' }}
      run: |
        echo -e $RELEASE_NOTES > release_notes.txt

    - name: Run ShipShape CLI
      shell: bash
      env:
        ICON_PATH: ${{ inputs.appIconPath }}
        DISTRIBUTION_LISTS: ${{ inputs.distributionListTargets }}
        SEND_PUSH: ${{ inputs.sendPush }}
        SEND_EMAIL: ${{ inputs.sendEmail }}
      run: ship publish --release-note release_notes.txt --distribution-list $DISTRIBUTION_LISTS --icon-path $ICON_PATH --send-push $SEND_PUSH --send-email $SEND_EMAIL --prompt false
