name: Render iOS App Icon Badge
description: Renders a badge on an iOS app icon.
branding:
  icon: square
  color: purple
inputs:
  search-dir:
    description: The directory to search for app icons.
    required: true
    default: .
  style:
    description: The style of the badge to be applied. Currently, only "beta" is available.
    required: true
    default: beta
  curl-color:
    description: A hex color to use for the curl effect, supported when the style is "beta". Automatically selects a color based on the color of the app icon when not specified.
    required: false
runs:
  using: composite
  steps:
  - name: Install Dependencies
    run: brew install --quiet pango jpeg librsvg
    shell: bash
  - name: Run Script
    uses: ./render-ios-app-icon-badge/script
    with:
      search-dir: ${{ inputs.search-dir }}
      style: ${{ inputs.style }}
      curl-color: ${{ inputs.curl-color }}
