name: Install SSH Key
description: Installs an SSH key
author: Simon B. Støvring
inputs:
  ssh-key:
    description: SSH private key contents.
    required: false
  ssh-key-base64:
    description: Base64-encoded SSH private key.
    required: false
  ssh-key-file:
    description: Path to an SSH private key file.
    required: false
  filename:
    description: Name of the file to store the key in.
    required: false
    default: id_rsa
  ssh-key-password:
    description: Password for the SSH key.
    required: false
runs:
  using: composite
  steps:
    - name: Install SSH Key
      run: |
        set -euo pipefail
        # Helper function used to cause ssh-add to timeout instead of hanging indefinitely upon error.
        function timeout() {
          perl -e 'alarm shift; exec @ARGV' "$@" > /dev/null 2>&1
        }
        
        # Configuration.
        SSH_KEY_PATH="$HOME/.ssh/${{ inputs.filename }}"
        SSH_ADD_TIMEOUT=5
        SSH_ADD_STATUS=0
        
        # Set SSH_AUTH_SOCK for all jobs
        export SSH_AUTH_SOCK="/tmp/ssh_agent.sock"
        echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV
        
        # Start the SSH agent, suppress error if already running
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null 2>&1 || true
        
        # Set password if needed.
        SSH_KEY_PASSWORD="${{ inputs.ssh-key-password }}"
        
        # Remove the SSH key if it exists.
        ssh-add -d "$SSH_KEY_PATH" &>/dev/null || true
        rm -f "$SSH_KEY_PATH"
        
        # Write the SSH key to disk.
        mkdir -p ~/.ssh
        if [[ -n "${{ inputs.ssh-key-base64 }}" ]]; then
          printf '%s' "${{ inputs.ssh-key-base64 }}" | openssl base64 -d -A -out "$SSH_KEY_PATH"
        elif [[ -n "${{ inputs.ssh-key }}" ]]; then
          printf '%s' "${{ inputs.ssh-key }}" > "$SSH_KEY_PATH"
        elif [[ -n "${{ inputs.ssh-key-file }}" ]]; then
          eval ssh_key_file="${{ inputs.ssh-key-file }}"
          cp "$ssh_key_file" "$SSH_KEY_PATH"
        else
          echo "Error: Provide ssh-key, ssh-key-base64, or ssh-key-file."
          exit 1
        fi
        chmod 600 "$SSH_KEY_PATH"
        
        # Install the SSH key either without a password or with one.
        if [ -z "$SSH_KEY_PASSWORD" ]; then
          timeout $SSH_ADD_TIMEOUT ssh-add $SSH_KEY_PATH || SSH_ADD_STATUS=$?
        else
          ASKPASS_SCRIPT=$(mktemp)
          chmod +x $ASKPASS_SCRIPT
          echo "#!/bin/bash" > $ASKPASS_SCRIPT
          echo "echo $SSH_KEY_PASSWORD" >> $ASKPASS_SCRIPT
          DISPLAY=1 SSH_ASKPASS=$ASKPASS_SCRIPT timeout $SSH_ADD_TIMEOUT ssh-add $SSH_KEY_PATH < /dev/null || SSH_ADD_STATUS=$?
          rm -f $ASKPASS_SCRIPT
        fi
        
        # Handle errors from invoking ssh-add.
        if [ $SSH_ADD_STATUS -ne 0 ]; then
          if [ -z "$SSH_KEY_PASSWORD" ]; then
            echo "::error::Failed to add the SSH key. No password was supplied. Is the SSH key password-protected?"
          else
            echo "::error::Failed to add the SSH key. It may be that the supplied password is incorrect."
          fi
          exit 1
        fi
      shell: bash
