name: Install SSH Key with 1Password
description: Installs a SSH key read from 1Password
author: Simon B. Støvring
inputs:
  op-reference:
    description: Reference to the SSH key in 1Password.
    required: true
  filename:
    description: Name of the file to store the key in.
    required: false
    default: id_rsa
  op-password-reference:
    description: Reference to the password for the SSH key in 1Password.
    required: false
runs:
  using: composite
  steps:
    - name: Install SSH Key
      run: |
        #!/bin/bash
        function timeout() {
          perl -e 'alarm shift; exec @ARGV' "$@" > /dev/null 2>&1
        }
        mkdir -p ~/.ssh
        SSH_KEY_PATH="$HOME/.ssh/${{ inputs.filename }}"
        SSH_KEY_PASSWORD="${{ inputs.op-password-reference }}"
        SSH_ADD_TIMEOUT=5
        op read --out-file $SSH_KEY_PATH "${{ inputs.op-reference }}"
        if [ -z "$SSH_KEY_PASSWORD" ]; then
          timeout $SSH_ADD_TIMEOUT ssh-add $SSH_KEY_PATH || SSH_ADD_STATUS=$?
        else
          ASKPASS_SCRIPT=$(mktemp)
          chmod +x $ASKPASS_SCRIPT
          echo "#!/bin/bash" > $ASKPASS_SCRIPT
          echo "echo $SSH_KEY_PASSWORD" >> $ASKPASS_SCRIPT
          DISPLAY=1 SSH_ASKPASS=$ASKPASS_SCRIPT timeout $SSH_ADD_TIMEOUT ssh-add $SSH_KEY_PATH < /dev/null || SSH_ADD_STATUS=$?
          rm -f $ASKPASS_SCRIPT
        fi
        echo $SSH_ADD_STATUS
        if [ $SSH_ADD_STATUS -ne 0 ]; then
          if [ -z "$SSH_KEY_PASSWORD" ]; then
            echo "::error::Failed to add SSH key. No password was supplied. Is the SSH key password protected?"
          else
            echo "::error::Failed to add SSH key. It may be that the supplied password is incorrect."
          fi
          exit 1
        fi
      shell: bash
