name: Jira issues changelog
description: Outputs a list of Jira issue keys mentioned in commit messages between the current commit you are at and the most recent tag that does not include the inputted app version.
author: Mathias Mortensen & Marcus Mattsson
inputs:
  jira-project-id:
    description: The Jira project ID, e.g. "OK"
    required: true
  marketing-version:
    description: The marketing version of the app you're building, e.g. "1.0.0"
    required: true
outputs:
  issues:
    description: The list of Jira issues mentioned in the changelog
    value: ${{ steps.changelog.outputs.issues }}
runs:
  using: composite
  steps:
    - name: Get Jira issues from changelog
      id: changelog
      run: |
        # Fetch all tags
        git fetch --tags origin

        # Read all tags, separate them into an array
        all_tags=`git tag -l | wc -l`
        
        if [ $all_tags = 0 ]; then
            # No tags, exit.
            echo "Repository contains no tags. Please make a tag first."
            exit 0
        else 
            echo "Fetching commits since last tag."

            # Get version
            version='${{ inputs.marketing-version }}'
            # Escape version for regex usage below
            escaped_version=$(echo $version | sed 's/\./\\./g')

            # Get latest tag that does not contain the current version number
            previous_tag="$(git describe --abbrev=0 --tags $(git tag -l --sort=-creatordate | grep -v $escaped_version | head -n 1))"        
            changelog="$(git log --pretty=format:"%s  (%cd) _<%ce>_" --date=format:"%Y-%m-%d %H:%M:%S" $previous_tag..HEAD)"
        fi
          
        # Output collected information
        echo "Previous tag: $previous_tag"
        
        # Identify Jira Issue, if multiple use ',' as delimiter
        jira_issues=$(echo "$changelog" | egrep -o '${{ inputs.jira-project-id }}-[0-9]+' | sort -uf | tr '\n' ',' | sed 's/.$//') || true

        # Check if any Jira issues were found
        if [ -z "$jira_issues" ]; then
            echo "No Jira issues found in the changelog."
            echo "::warning title=Warning!::No Jira issues found in the changelog"
            exit 0
        else
            echo "Found the following issues in the changelog: $jira_issues"
        fi

        # Check if GITHUB_OUTPUT is set
        if [ -n "$GITHUB_OUTPUT" ]; then
            echo "issues=$jira_issues" >> "$GITHUB_OUTPUT"
        else
            echo "GITHUB_OUTPUT is not set. Outputting to console instead."
            echo "issues=$jira_issues"
        fi

        # Ensure the script exits successfully
        exit 0
      shell: bash
