name: Post Slack Message
inputs:
  channel:
    description: Slack channel to post message in
    required: true
  message:
    description: Message to post
    required: true
  op-slack-token-reference:
    description: Slack access token reference
    required: true
runs:
  using: composite
  steps:
    - name: Post to Slack
      run: |
        pwd
        echo ${{ github.action_path }}

        slack_token=$(op read "${{ inputs.op-slack-token-reference }}")
        job_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        cd Slacker
        swift run Slacker "${{ inputs.channel }}" "${{ inputs.message }}" "${{ github.workflow }}" "${{ runner.name }}" "${{ github.ref_name }}" "${{ github.ref_type }}" "${{ github.actor }}" "${job_url}" "${slack_token}"
      shell: bash