name: Post Slack Message
inputs:
  channel:
    description: Slack channel to post message in
    required: true
  message:
    description: Message to post
    required: true
  op-slack-token-reference:
    description: Slack access token reference
    required: true
runs:
  using: composite
  steps:
    - name: Post to Slack
      run: |
        slack_token=$(op read "${{ inputs.op-slack-token-reference }}")
        job_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        cd "${{ github.action_path }}/Slacker"
        swift run Slacker --channel "${{ inputs.channel }}" --token "${slack_token}" --message "${{ inputs.message }}" --fields "Workflow:${{ github.workflow }}" "Runner:${{ runner.name }}" "Branch:${{ github.ref_name }}" "Started by:${{ github.actor }}" --job-url "{job_url}"
      shell: bash