name: Install Certificate
description: Installs a certificate in the keychain.
author: Simon B. Støvring
inputs:
  password-op-reference:
    description: Reference to the password for the certificate in 1Password.
    required: true
  certificate-op-reference:
    description: Reference to the certificate in 1Password.
    required: true
  keychain-name:
    description: Name of the keychain to add the certificate to. The keychain will be created if it does not exist.
    required: false
    default: build.keychain
  keychain-password:
    description: Password of the keychain to add the certificate to. Fallback to a randomly generated password if not set or empty.
    required: false
  set-default-keychain:
    description: Set the keychain as the default keychain.
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Install Certificate
      run: |
        CERTIFICATE_PASSWORD=$(op read "${{ inputs.password-op-reference }}")
        CERTIFICATE_FILE_PATH=$(uuidgen).p12
        INPUT_KEYCHAIN_PASSWORD_VALUE="${{ inputs.keychain-password }}"
        KEYCHAIN_PASSWORD="${INPUT_KEYCHAIN_PASSWORD_VALUE:-$(uuidgen)}"
        KEYCHAIN_NAME="${{ inputs.keychain-name }}"
        KEYCHAIN_PATH="/Users/$(whoami)/Library/Keychains/${KEYCHAIN_NAME}"
        KEYCHAIN_DB_PATH="${KEYCHAIN_PATH}-db"
        if [ -z "$CERTIFICATE_PASSWORD" ]; then
          echo "::error::The password for the certificate cannot be empty."
          exit 1
        fi
        op read --out-file $CERTIFICATE_FILE_PATH "${{ inputs.certificate-op-reference }}"
        CERTIFICATE_PEM_PATH=$(mktemp)
        OPENSSL_VERSION=$(openssl version)
        if echo "$OPENSSL_VERSION" | grep -qE 'OpenSSL 3'; then
          OPENSSL_PKCS12_FLAGS="-legacy"
        else
          OPENSSL_PKCS12_FLAGS=""
        fi
        if ! OPENSSL_PKCS12_OUTPUT=$(openssl pkcs12 $OPENSSL_PKCS12_FLAGS -in "$CERTIFICATE_FILE_PATH" -clcerts -nokeys -passin pass:"$CERTIFICATE_PASSWORD" -out "$CERTIFICATE_PEM_PATH" 2>&1); then
          printf '%s\n' "$OPENSSL_PKCS12_OUTPUT"
          echo "::error::Failed to read certificate file. Check that the certificate and password are correct."
          rm -f "$CERTIFICATE_PEM_PATH"
          exit 1
        fi
        CERTIFICATE_EXPIRY=$(openssl x509 -in "$CERTIFICATE_PEM_PATH" -noout -enddate | cut -d= -f2)
        if ! openssl x509 -in "$CERTIFICATE_PEM_PATH" -noout -checkend 0 >/dev/null 2>&1; then
          echo "::error::The certificate at '${{ inputs.certificate-op-reference }}' has expired on $CERTIFICATE_EXPIRY."
          rm -f "$CERTIFICATE_PEM_PATH"
          exit 1
        fi
        if ! openssl x509 -in "$CERTIFICATE_PEM_PATH" -noout -checkend 2592000 >/dev/null 2>&1; then
          echo "::warning::The certificate at '${{ inputs.certificate-op-reference }}' will expire soon (on $CERTIFICATE_EXPIRY)."
        fi
        if [ ! -f "$KEYCHAIN_DB_PATH" ]; then
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychains -d user -s $KEYCHAIN_DB_PATH $(security list-keychains -d user | sed s/\"//g)
          security set-keychain-settings "$KEYCHAIN_NAME"
        fi
        security import $CERTIFICATE_FILE_PATH -k "$KEYCHAIN_NAME" -f pkcs12 -A -T /usr/bin/codesign -T /usr/bin/security -P $CERTIFICATE_PASSWORD
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
        if [ "${{ inputs.set-default-keychain }}" = true ]; then
          security default-keychain -s $KEYCHAIN_PATH
        fi
        rm -f "$CERTIFICATE_PEM_PATH"
        rm $CERTIFICATE_FILE_PATH
      shell: bash
