name: Install Certificate
description: Installs a certificate in the keychain.
author: Simon B. Støvring
inputs:
  password-op-reference:
    description: Reference to the password for the certificate in 1Password.
    required: true
  certificate-op-reference:
    description: Reference to the certificate in 1Password.
    required: true
runs:
  using: composite
  steps:
    - name: Install Certificate
      run: |
        CERTIFICATE_PASSWORD=$(op read "${{ inputs.password-op-reference }}")
        CERTIFICATE_FILE_PATH=$(uuidgen).p12
        KEYCHAIN_PASSWORD=$(uuidgen)
        KEYCHAIN_NAME="build.keychain"
        KEYCHAIN_PATH="/Users/$(whoami)/Library/Keychains/${KEYCHAIN_NAME}"
        KEYCHAIN_DB_PATH="${KEYCHAIN_PATH}-db"
        op read --out-file $CERTIFICATE_FILE_PATH "${{ inputs.certificate-op-reference }}"
        if [ ! -f "$KEYCHAIN_DB_PATH" ]; then
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychains -d user -s $KEYCHAIN_DB_PATH $(security list-keychains -d user | sed s/\"//g)
          security set-keychain-settings "$KEYCHAIN_NAME"
        fi
        security import $CERTIFICATE_FILE_PATH -k "$KEYCHAIN_NAME" -f pkcs12 -A -T /usr/bin/codesign -T /usr/bin/security -P $CERTIFICATE_PASSWORD
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
        security default-keychain -s $KEYCHAIN_PATH
        rm $CERTIFICATE_FILE_PATH
      shell: bash
